version: '3'
services:
  db:
    image: postgres:13
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookmarks
    networks:
      - bookmarks-app
networks:
  bookmarks-app: